build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm
labels:
  org.opencontainers.image.title: "God's Eye View"
  org.opencontainers.image.description: "Home Assistant add-on wrapping God's Eye View"
  org.opencontainers.image.source: "https://github.com/jstockley/gods-eye-view-ha"
